//
// Created by Alexander Powers on /1212/19.
//

#ifndef TEMPERATUREDISPLAY_ENUMPRESETTABSELECTSETTING_H
#define TEMPERATUREDISPLAY_ENUMPRESETTABSELECTSETTING_H
enum PresetTabSelectSetting {
    ONE,
    TWO,
    THREE,
    FOUR,
};
#endif //TEMPERATUREDISPLAY_ENUMPRESETTABSELECTSETTING_H
