//
// Created by Alexander Powers on /1212/19.
//

#ifndef TEMPERATUREDISPLAY_CONTROLSETTING_H
#define TEMPERATUREDISPLAY_CONTROLSETTING_H
enum ControlSetting {
    OFF,
    AUTO,
    HEAT,
    ON
};
#endif //TEMPERATUREDISPLAY_CONTROLSETTING_H
