//
// Created by Alexander Powers on /1212/19.
//

#ifndef TEMPERATUREDISPLAY_ENUMSCREENSETTING_H
#define TEMPERATUREDISPLAY_ENUMSCREENSETTING_H
enum ScreenSetting {
    MAIN,
    PRESET_SELECT_SET,
    PRESET_SET,
    CLOCK_SET
};
#endif //TEMPERATUREDISPLAY_ENUMSCREENSETTING_H
