//
// Created by Alexander Powers on /1212/19.
//

#ifndef TEMPERATUREDISPLAY_ENUMPRESETSELECTSETSETTING_H
#define TEMPERATUREDISPLAY_ENUMPRESETSELECTSETSETTING_H
enum PresetSelectSetSetting {
    WEEKEND,
    WEEKDAY,
};
#endif //TEMPERATUREDISPLAY_ENUMPRESETSELECTSETSETTING_H
