//
// Created by Alexander Powers on /1212/19.
//

#ifndef TEMPERATUREDISPLAY_ENUMDAYOFWEEK_H
#define TEMPERATUREDISPLAY_ENUMDAYOFWEEK_H

enum Days {
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY
};


#endif //TEMPERATUREDISPLAY_ENUMDAYOFWEEK_H
